name: Windows Release

# 在提供 version 标签的时候启动编译
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-rust@v1
        with:
          target: x86_64-pc-windows-gnu
          override: true

      - run: cargo build --release --target x86_64-pc-windows-gnu

      - uses: dawidd6/action-zip@v2
        with:
          root: target/x86_64-pc-windows-gnu/release
          output: todo-${{ github.ref_name }}.zip

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: todo-${{ github.ref_name }}.zip
