name: Windows Release

# 在提供 version 标签的时候启动编译
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
   create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
   upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: x86_64-pc-windows-gnu
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: todo-cli
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}